// @ts-expect-error — generated by OpenNext build
import openNextWorker from "../.open-next/worker.js";

// @ts-expect-error — generated by OpenNext build
export {
  DOQueueHandler,
  DOShardedTagCache,
  BucketCachePurge,
} from "../.open-next/worker.js";

type CronEnv = {
  CACHE_REVALIDATE_SECRET?: string;
  CRON_WORKER_BASE_URL?: string;
};

async function triggerDailyOfficialCrawl(env: CronEnv) {
  const secret = env.CACHE_REVALIDATE_SECRET;
  if (!secret) {
    console.error("[cron] CACHE_REVALIDATE_SECRET is not configured");
    return;
  }

  const baseUrl = env.CRON_WORKER_BASE_URL?.trim();
  if (!baseUrl) {
    console.error("[cron] CRON_WORKER_BASE_URL is not configured");
    return;
  }
  const url = new URL("/api/cron/daily-official-crawl", baseUrl);

  const response = await fetch(url, {
    method: "POST",
    headers: {
      Authorization: `Bearer ${secret}`,
      "User-Agent": "vn-insurance-fti-cron/1.0",
    },
  });

  if (!response.ok) {
    const body = await response.text();
    console.error("[cron] daily-official-crawl failed", response.status, body);
    return;
  }

  console.info("[cron] daily-official-crawl completed", await response.text());
}

export default {
  async fetch(
    request: Request,
    env: CronEnv,
    ctx: { waitUntil(promise: Promise<unknown>): void },
  ) {
    return openNextWorker.fetch(request, env, ctx);
  },
  async scheduled(
    _controller: unknown,
    env: CronEnv,
    ctx: { waitUntil(promise: Promise<unknown>): void },
  ) {
    ctx.waitUntil(triggerDailyOfficialCrawl(env));
  },
};
